import React from 'react';
import {UserProvider} from '@auth0/nextjs-auth0/client';
import {getSession} from '@auth0/nextjs-auth0';
import type {Metadata} from 'next';
import {Rubik as font} from 'next/font/google';
import './globals.css';
import GlobalStateProvider from '@/app/context';

const rubik = font({
	weight: '400',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'People and Friends Network',
	description: 'Generated by create Next app, MongoDb, Auth0'
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
	const session = await getSession();

	return (
		<html lang="en">
		<UserProvider>
			<body className={rubik.className}>
			<header>
				{session?.user && (
					<div>
						{session.user.email}
						<a className="flex flex-col items-center heading2 w-fit m-auto" href="/api/auth/logout">
							Logout
						</a>
					</div>
				)}
			</header>
			<GlobalStateProvider>
				<main>{children}</main>
			</GlobalStateProvider>
			</body>
		</UserProvider>
		</html>
	);
}
